### ISSUE TITLE
[Feature]: Config option for precision limit

### ISSUE THREAD

**Issue by DemonSlayer112** [tristankechlo/RandomMobSizes#17]
### What is your idea?

I notice so far the mod picks a random floating point number with around 7 places of precision.
Can we have a choice to how precise we want?
If so, we can define `0.1` to 1 place of precision, or perhaps even config the steps? like every 0.05. 1.0, 1.05, 1.1

This way i can make events via kubejs setting the size based on conditions, but being able to get a true 1.0 at somepoint again.

**Comment by tristankechlo** [comment]
I understand why it might be useful to compare values ​​for further scripts,
but I think it's not a good idea to compare floating point numbers for equality (the comparison might not be predictable due to precision errors in floating point numbers).

Maybe you can check in your scripts if the value is within a defined range.
e.g. `1.049 < x && x < 1.051`
